coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
        base: auto
        # advanced settings
        branches:
          - main
        if_ci_failed: error
        informational: false
        only_pulls: false
