coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        # temporary ignore the target
        # target: 50%
        informational: true
