name: Check if the Pull Request can be merged

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  can-merge-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install

      - run: npm run lint:check

      - run: npm run format:check

      - run: npm run test

      - run: npm run build
